### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kwonoj** [kwonoj/libsass-asm#31]
- [x] webpack sourcemap issue
- [x] rename 'mount' to 'root' or something else
- [x] compilecache or v8 snapshot
- [ ] `renderSync` interface?
- [ ] easier mount handling for `render`? (cli does mount externally from `compile`)
- [x] test failure
- [ ] sass-spec configuration
